# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '000-ViewsAndControl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit'
  # Pods for 000-ViewsAndControl

end
